import type { ResearchGraphState } from '../types';

export const DEMO_INVESTIGATION_STATE: ResearchGraphState = {
  session_id: 'SES-DEMO-ALZ-01',
  research_question: "Identify promising therapeutic targets for Alzheimer's disease.",
  disease_name: "Alzheimer's disease",
  disease_efo_id: 'EFO_0000249',
  created_at: new Date().toISOString(),
  current_stage: 'supervisor_synthesis',
  status: 'completed',
  scoring_weights: {
    disease_association: 0.25,
    genetic_evidence: 0.20,
    target_tractability: 0.20,
    literature_evidence: 0.15,
    experimental_validation: 0.10,
    safety_profile: 0.10,
  },
  enable_compound_screening: true,
  max_literature_results: 15,
  top_n_targets_to_screen: 5,
  executive_summary:
    "Comprehensive multi-agent investigation prioritized 5 high-potential therapeutic targets for Alzheimer's disease. TREM2 and BACE1 demonstrate the highest combined genetic, clinical, and tractability scores, with TREM2 favored due to strong causal microglial variants (R47H) and clinical antibody validation.",
  retrieved_papers: [
    {
      pmid: '31234567',
      doi: '10.1038/s41586-019-1234-5',
      title: 'Microglial TREM2 activation restores cognitive deficits and reduces tau propagation',
      journal: 'Nature Medicine',
      publication_year: 2021,
      authors: ['Smith J', 'Doe A', 'Karch CM'],
      mesh_terms: ['Alzheimer Disease', 'Microglia', 'TREM2 Protein', 'Immunotherapy'],
      abstract:
        'Triggering receptor expressed on myeloid cells 2 (TREM2) is a key regulator of microglial fitness and response to amyloid plaques and neurofibrillary tangles. Agonistic antibody intervention preserves cognitive function in transgenic murine models.',
    },
    {
      pmid: '29876543',
      doi: '10.1016/j.cell.2020.04.012',
      title: 'Structural basis of BACE1 inhibition and peripheral safety considerations',
      journal: 'Cell',
      publication_year: 2020,
      authors: ['Vassar R', 'Citron M'],
      mesh_terms: ['Amyloid Precursor Protein Secretases', 'Aspartic Acid Endopeptidases', 'BACE1'],
      abstract:
        'Beta-secretase 1 (BACE1) initiates the cleavage of amyloid precursor protein. While small-molecule inhibitors achieve potent brain penetrance, cognitive worsening in clinical trials necessitates selective partial inhibition or substrate-specific targeting.',
    },
    {
      pmid: '33445566',
      doi: '10.1056/NEJMoa2100502',
      title: 'Apolipoprotein E (APOE) epsilon 4 allele dose and neurovascular decoupling',
      journal: 'New England Journal of Medicine',
      publication_year: 2022,
      authors: ['Holtzman DM', 'Mahley RW'],
      mesh_terms: ['Apolipoprotein E4', 'Blood-Brain Barrier', 'Dementia'],
      abstract:
        'APOE4 remains the strongest genetic risk factor for sporadic Alzheimer disease, impairing lipid homeostasis, blood-brain barrier integrity, and microglial amyloid clearance.',
    },
  ],
  identified_targets: {
    TREM2: {
      symbol: 'TREM2',
      name: 'Triggering Receptor Expressed On Myeloid Cells 2',
      ensembl_id: 'ENSG00000095977',
      disease_association_score: 0.94,
    },
    BACE1: {
      symbol: 'BACE1',
      name: 'Beta-Secretase 1',
      ensembl_id: 'ENSG00000186318',
      disease_association_score: 0.91,
    },
    APOE: {
      symbol: 'APOE',
      name: 'Apolipoprotein E',
      ensembl_id: 'ENSG00000130203',
      disease_association_score: 0.98,
    },
    APP: {
      symbol: 'APP',
      name: 'Amyloid Beta Precursor Protein',
      ensembl_id: 'ENSG00000142192',
      disease_association_score: 0.89,
    },
    PSEN1: {
      symbol: 'PSEN1',
      name: 'Presenilin 1',
      ensembl_id: 'ENSG00000080815',
      disease_association_score: 0.88,
    },
  },
  druggability_assessments: {
    TREM2: {
      target_symbol: 'TREM2',
      overall_tractability_score: 86.5,
      modalities: {
        Antibody: {
          modality: 'Antibody',
          bucket: 'Clinical Precedence',
          top_category: 'Phase II Monoclonal Antibody (AL002)',
          has_clinical_precedence: true,
        },
        'Small Molecule': {
          modality: 'Small Molecule',
          bucket: 'Discovery Opportunity',
          top_category: 'Positive Allosteric Modulators',
        },
      },
      antibody_tractable: true,
      small_molecule_tractable: false,
    },
    BACE1: {
      target_symbol: 'BACE1',
      overall_tractability_score: 91.0,
      modalities: {
        'Small Molecule': {
          modality: 'Small Molecule',
          bucket: 'Clinical Precedence',
          top_category: 'Potent Active-Site Peptidomimetics',
          has_clinical_precedence: true,
        },
      },
      small_molecule_tractable: true,
      antibody_tractable: false,
    },
    APOE: {
      target_symbol: 'APOE',
      overall_tractability_score: 62.0,
      modalities: {
        Antibody: {
          modality: 'Antibody',
          bucket: 'Clinical Precedence',
          top_category: 'Anti-APOE4 clearing antibodies',
        },
        'Small Molecule': {
          modality: 'Small Molecule',
          bucket: 'Discovery Opportunity',
          top_category: 'Structure correctors',
        },
      },
      small_molecule_tractable: false,
      antibody_tractable: true,
    },
    APP: {
      target_symbol: 'APP',
      overall_tractability_score: 75.0,
      modalities: {
        Antibody: {
          modality: 'Antibody',
          bucket: 'Approved Drug',
          top_category: 'Lecanemab, Donanemab (Anti-Aβ protofibrils)',
          has_approved_drug: true,
        },
      },
      antibody_tractable: true,
    },
    PSEN1: {
      target_symbol: 'PSEN1',
      overall_tractability_score: 58.0,
      modalities: {
        'Small Molecule': {
          modality: 'Small Molecule',
          bucket: 'Literature Precedence',
          top_category: 'Gamma-secretase modulators (GSMs)',
        },
      },
      small_molecule_tractable: true,
    },
  },
  target_rankings: [
    {
      target_symbol: 'TREM2',
      target_name: 'Triggering Receptor Expressed On Myeloid Cells 2',
      ensembl_id: 'ENSG00000095977',
      disease_name: "Alzheimer's disease",
      overall_priority_score: 89.4,
      confidence_tier: 'high',
      confidence_score: 0.92,
      tractability_summary: 'Antibody Clinical Precedence (Phase II)',
      experimental_validation_status: 'Validated in In Vitro & Transgenic Models',
      evidence_count: 5,
      biological_rationale:
        'Transmembrane immune receptor critically mediating microglial clearance of neurotoxic oligomers and compacting amyloid core morphology. Rare R47H missense variant confers 3-4x increased disease susceptibility.',
      safety_concerns: ['Systemic inflammatory hypersensitivity', 'Off-target myeloid cell activation'],
      recommended_modalities: ['Agonistic Monoclonal Antibody', 'Bispecific Receptor Activator'],
      score_breakdown: {
        disease_association_score: 94.0,
        genetic_evidence_score: 96.0,
        target_tractability_score: 86.5,
        literature_evidence_score: 88.0,
        experimental_validation_score: 82.0,
        safety_profile_score: 90.0,
        contradiction_penalty: 0.0,
        raw_composite_score: 89.4,
        final_clamped_score: 89.4,
      },
    },
    {
      target_symbol: 'BACE1',
      target_name: 'Beta-Secretase 1',
      ensembl_id: 'ENSG00000186318',
      disease_name: "Alzheimer's disease",
      overall_priority_score: 82.1,
      confidence_tier: 'high',
      confidence_score: 0.85,
      tractability_summary: 'Small Molecule Clinical Precedence',
      experimental_validation_status: 'Extensively Validated Enzymatic Target',
      evidence_count: 6,
      biological_rationale:
        'Rate-limiting aspartyl protease catalyzing the initial amyloidogenic cleavage of APP to generate Aβ40 and Aβ42 peptides.',
      safety_concerns: ['Cognitive worsening at >50% inhibition', 'Retinal and peripheral axon myelin thinning (NRG1 cleavage)'],
      recommended_modalities: ['Low-dose partial inhibitor', 'Substrate-selective allosteric inhibitor'],
      score_breakdown: {
        disease_association_score: 91.0,
        genetic_evidence_score: 88.0,
        target_tractability_score: 91.0,
        literature_evidence_score: 85.0,
        experimental_validation_score: 90.0,
        safety_profile_score: 60.0,
        contradiction_penalty: 5.0,
        raw_composite_score: 82.1,
        final_clamped_score: 82.1,
      },
    },
    {
      target_symbol: 'APP',
      target_name: 'Amyloid Beta Precursor Protein',
      ensembl_id: 'ENSG00000142192',
      disease_name: "Alzheimer's disease",
      overall_priority_score: 79.5,
      confidence_tier: 'medium',
      confidence_score: 0.78,
      tractability_summary: 'Antibody Approved Drug (Protofibrils)',
      experimental_validation_status: 'Clinically Validated Biomarker Target',
      evidence_count: 4,
      biological_rationale:
        'Integral membrane glycoprotein giving rise to amyloid fibrils upon proteolysis. Pathogenic dominant mutations cluster around cleavage sites.',
      safety_concerns: ['Amyloid-related imaging abnormalities (ARIA-E / ARIA-H)'],
      recommended_modalities: ['Conformation-specific Monoclonal Antibody'],
      score_breakdown: {
        disease_association_score: 89.0,
        genetic_evidence_score: 92.0,
        target_tractability_score: 75.0,
        literature_evidence_score: 80.0,
        experimental_validation_score: 78.0,
        safety_profile_score: 65.0,
        contradiction_penalty: 0.0,
        raw_composite_score: 79.5,
        final_clamped_score: 79.5,
      },
    },
    {
      target_symbol: 'APOE',
      target_name: 'Apolipoprotein E',
      ensembl_id: 'ENSG00000130203',
      disease_name: "Alzheimer's disease",
      overall_priority_score: 73.8,
      confidence_tier: 'medium',
      confidence_score: 0.72,
      tractability_summary: 'Antibody Clinical Precedence / Low SM Tractability',
      experimental_validation_status: 'Validated in Target Discovery Studies',
      evidence_count: 4,
      biological_rationale:
        'Primary apolipoprotein of the brain. Isoform epsilon-4 exerts pleiotropic toxic gain of function, impairing lipid processing and neuronal synaptogenesis.',
      safety_concerns: ['Lipid homeostasis disruption', 'Systemic hypercholesterolemia risk'],
      recommended_modalities: ['Selective Anti-APOE4 Monoclonal Antibody', 'ASO/siRNA knockdown'],
      score_breakdown: {
        disease_association_score: 98.0,
        genetic_evidence_score: 98.0,
        target_tractability_score: 62.0,
        literature_evidence_score: 78.0,
        experimental_validation_score: 65.0,
        safety_profile_score: 70.0,
        contradiction_penalty: 0.0,
        raw_composite_score: 73.8,
        final_clamped_score: 73.8,
      },
    },
    {
      target_symbol: 'PSEN1',
      target_name: 'Presenilin 1',
      ensembl_id: 'ENSG00000080815',
      disease_name: "Alzheimer's disease",
      overall_priority_score: 68.2,
      confidence_tier: 'low',
      confidence_score: 0.62,
      tractability_summary: 'Literature Precedence / Intramembrane Complexity',
      experimental_validation_status: 'Validated In Vitro Enzyme Complex',
      evidence_count: 3,
      biological_rationale:
        'Catalytic subunit of the intramembrane gamma-secretase complex. Causative familial mutations skew Aβ42:Aβ40 ratio towards aggregation-prone forms.',
      safety_concerns: ['Notch signaling inhibition causing intestinal toxicity and skin lesions'],
      recommended_modalities: ['Gamma-Secretase Modulator (GSM, non-inhibitory)'],
      score_breakdown: {
        disease_association_score: 88.0,
        genetic_evidence_score: 90.0,
        target_tractability_score: 58.0,
        literature_evidence_score: 70.0,
        experimental_validation_score: 60.0,
        safety_profile_score: 45.0,
        contradiction_penalty: 6.0,
        raw_composite_score: 68.2,
        final_clamped_score: 68.2,
      },
    },
  ],
  evidence_records: [
    {
      evidence_id: 'EV-TREM2-01',
      target_symbol: 'TREM2',
      evidence_type: 'genetic_association',
      source_database: 'Open Targets / GWAS Catalog',
      causality_level: 'direct_causal_variant',
      is_contradictory: false,
      summary_snippet: 'TREM2 R47H variant significantly impairs ligand sensing and microglial survival, OR = 3.4.',
      citation: {
        pmid: '23151322',
        title: 'Variant of TREM2 associated with the risk of Alzheimer disease',
        journal: 'N Engl J Med',
        publication_year: 2013,
      },
      confidence_score: 0.95,
      data_origin: 'opentargets_graphql',
    },
    {
      evidence_id: 'EV-TREM2-02',
      target_symbol: 'TREM2',
      evidence_type: 'literature_cooccurrence',
      source_database: 'PubMed',
      causality_level: 'functional_association',
      is_contradictory: false,
      summary_snippet: 'Agonistic TREM2 antibody AL002 promotes microglial trophic signaling and lowers tau deposition.',
      citation: {
        pmid: '31234567',
        title: 'Microglial TREM2 activation restores cognitive deficits and reduces tau propagation',
        journal: 'Nature Medicine',
        publication_year: 2021,
      },
      confidence_score: 0.88,
      data_origin: 'ncbi_eutils',
    },
    {
      evidence_id: 'EV-BACE1-01',
      target_symbol: 'BACE1',
      evidence_type: 'genetic_association',
      source_database: 'ClinVar / Open Targets',
      causality_level: 'protective_variant',
      is_contradictory: false,
      summary_snippet: 'Icelandic APP A673T mutation near BACE1 cleavage site confers strong protection against Alzheimer dementia.',
      citation: {
        pmid: '22786448',
        title: 'A mutation in APP protects against Alzheimer disease and age-related cognitive decline',
        journal: 'Nature',
        publication_year: 2012,
      },
      confidence_score: 0.92,
      data_origin: 'opentargets_graphql',
    },
    {
      evidence_id: 'EV-BACE1-02',
      target_symbol: 'BACE1',
      evidence_type: 'clinical_trial_reversal',
      source_database: 'PubMed',
      causality_level: 'safety_contraindication',
      is_contradictory: true,
      summary_snippet: 'Verubecestat Phase 3 trial was halted prematurely due to mechanism-based cognitive worsening in mild-to-moderate patients.',
      citation: {
        pmid: '29876543',
        title: 'Randomized Trial of Verubecestat for Prodromal Alzheimer Disease',
        journal: 'N Engl J Med',
        publication_year: 2019,
      },
      confidence_score: 0.85,
      data_origin: 'ncbi_eutils',
    },
    {
      evidence_id: 'EV-APOE-01',
      target_symbol: 'APOE',
      evidence_type: 'genetic_association',
      source_database: 'GWAS Catalog',
      causality_level: 'direct_causal_variant',
      is_contradictory: false,
      summary_snippet: 'APOE4 homozygosity increases lifetime risk of dementia over twelve-fold compared to APOE3/3.',
      citation: {
        pmid: '33445566',
        title: 'Apolipoprotein E (APOE) epsilon 4 allele dose and neurovascular decoupling',
        journal: 'N Engl J Med',
        publication_year: 2022,
      },
      confidence_score: 0.98,
      data_origin: 'opentargets_graphql',
    },
  ],
  known_active_compounds: {
    TREM2: [
      {
        compound_id: 'CHEMBL4297812',
        compound_name: 'TREM2 Agonist mAb Mimetic',
        target_symbol: 'TREM2',
        activity_type: 'EC50',
        activity_value: 14.2,
        activity_unit: 'nM',
        source_database: 'ChEMBL v33',
        chembl_assay_id: 'CHEMBL_ASSAY_88921',
      },
      {
        compound_id: 'CHEMBL4089123',
        compound_name: 'DAP12 Coreceptor Stabilizer',
        target_symbol: 'TREM2',
        activity_type: 'Kd',
        activity_value: 38.0,
        activity_unit: 'nM',
        source_database: 'ChEMBL v33',
      },
    ],
    BACE1: [
      {
        compound_id: 'CHEMBL2105755',
        compound_name: 'Verubecestat (MK-8931)',
        target_symbol: 'BACE1',
        activity_type: 'IC50',
        activity_value: 2.2,
        activity_unit: 'nM',
        source_database: 'ChEMBL v33',
        chembl_assay_id: 'CHEMBL_ASSAY_44120',
      },
      {
        compound_id: 'CHEMBL3545124',
        compound_name: 'Atabecestat (JNJ-54861911)',
        target_symbol: 'BACE1',
        activity_type: 'IC50',
        activity_value: 4.8,
        activity_unit: 'nM',
        source_database: 'ChEMBL v33',
      },
      {
        compound_id: 'CHEMBL3128910',
        compound_name: 'Lanabecestat (AZD3293)',
        target_symbol: 'BACE1',
        activity_type: 'IC50',
        activity_value: 0.6,
        activity_unit: 'nM',
        source_database: 'ChEMBL v33',
      },
    ],
  },
  compound_screenings: {
    TREM2: [
      {
        target_symbol: 'TREM2',
        compound_id: 'SIM_LIGAND_TRM_01',
        predicted_kd_nm: 24.5,
        docking_score_kcal_mol: -9.8,
        affinity_tier: 'High Predicted Affinity (<100 nM)',
        method: 'AutoDock Vina In Silico Simulation',
        provenance_note: 'Screened against TREM2 Ig-like domain PDB:5ELI binding pocket',
        disclaimer: 'Computational simulation prediction — not experimentally measured.',
      },
      {
        target_symbol: 'TREM2',
        compound_id: 'SIM_LIGAND_TRM_02',
        predicted_kd_nm: 89.2,
        docking_score_kcal_mol: -8.4,
        affinity_tier: 'Moderate Affinity (100–1000 nM)',
        method: 'AutoDock Vina In Silico Simulation',
        disclaimer: 'Computational simulation prediction — not experimentally measured.',
      },
    ],
    BACE1: [
      {
        target_symbol: 'BACE1',
        compound_id: 'SIM_LIGAND_BAC_01',
        predicted_kd_nm: 12.8,
        docking_score_kcal_mol: -10.4,
        affinity_tier: 'High Predicted Affinity (<100 nM)',
        method: 'AutoDock Vina In Silico Simulation',
        provenance_note: 'Catalytic dyad Asp32/Asp228 docking model',
        disclaimer: 'Computational simulation prediction — not experimentally measured.',
      },
      {
        target_symbol: 'BACE1',
        compound_id: 'SIM_LIGAND_BAC_02',
        predicted_kd_nm: 145.0,
        docking_score_kcal_mol: -7.9,
        affinity_tier: 'Moderate Affinity (100–1000 nM)',
        method: 'AutoDock Vina In Silico Simulation',
        disclaimer: 'Computational simulation prediction — not experimentally measured.',
      },
    ],
  },
  experimental_data_matches: {
    TREM2: [
      {
        experiment_id: 'EXP-SYN-TRM-01',
        target_symbol: 'TREM2',
        assay_type: 'Surface Plasmon Resonance (SPR)',
        measurement_type: 'Kd',
        measured_value: 28.5,
        unit: 'nM',
        cell_line_or_model: 'Recombinant human TREM2 extracellular domain',
        validation_status: 'Hit Confirmed',
        is_synthetic: true,
        data_origin: 'synthetic_bench_assays',
      },
      {
        experiment_id: 'EXP-SYN-TRM-02',
        target_symbol: 'TREM2',
        assay_type: 'Microglial Phagocytosis Flow Assay',
        measurement_type: 'Aβ Uptake Induction',
        measured_value: 215.0,
        unit: '% of basal control',
        cell_line_or_model: 'Primary human iPSC-derived microglia',
        validation_status: 'Functionally Validated',
        is_synthetic: true,
        data_origin: 'synthetic_bench_assays',
      },
    ],
    BACE1: [
      {
        experiment_id: 'EXP-SYN-BAC-01',
        target_symbol: 'BACE1',
        assay_type: 'FRET Peptide Cleavage Assay',
        measurement_type: 'IC50',
        measured_value: 3.1,
        unit: 'nM',
        cell_line_or_model: 'Purified human recombinant BACE1 ectodomain',
        validation_status: 'Enzymatically Validated',
        is_synthetic: true,
        data_origin: 'synthetic_bench_assays',
      },
    ],
  },
  audit_trace: [
    {
      stage: 'supervisor_plan',
      agent_name: 'SupervisorAgent',
      input_summary: "Research question: 'Identify promising therapeutic targets for Alzheimer\\'s disease.'",
      output_summary: 'Target pathology normalized to Alzheimer disease; formulated 8-stage execution graph with compound screening enabled.',
      tool_calls: ['extract_disease_name', 'initialize_investigation_state'],
      status: 'success',
      duration_ms: 12.4,
      timestamp: '2026-10-02T07:20:00Z',
    },
    {
      stage: 'literature_search',
      agent_name: 'LiteratureSearchAgent',
      input_summary: 'Formulated MeSH search query for Alzheimer disease targets and therapeutic precedents.',
      output_summary: 'Retrieved 15 relevant PubMed peer-reviewed publications; extracted abstracts and DOIs.',
      tool_calls: ['ncbi_esearch', 'ncbi_efetch'],
      status: 'success',
      duration_ms: 840.5,
      timestamp: '2026-10-02T07:20:01Z',
    },
    {
      stage: 'target_identification',
      agent_name: 'TargetIdentificationAgent',
      input_summary: 'Scanned PubMed corpus & Open Targets association graphs for therapeutic targets.',
      output_summary: 'Identified 5 candidate targets (TREM2, BACE1, APP, APOE, PSEN1) across neuroinflammation, amyloid, and tau axes.',
      tool_calls: ['opentargets_disease_targets', 'nlp_entity_tagger'],
      status: 'success',
      duration_ms: 1240.2,
      timestamp: '2026-10-02T07:20:03Z',
    },
    {
      stage: 'evidence_evaluation',
      agent_name: 'EvidenceEvaluationAgent',
      input_summary: 'Evaluated genetic causal links, GWAS hits, and contradictory clinical trial outcomes.',
      output_summary: 'Collated 5 multi-modal evidence items; flagged BACE1 cognitive worsening trial reversal as contradiction.',
      tool_calls: ['classify_causality', 'extract_clinical_flags'],
      status: 'success',
      duration_ms: 450.1,
      timestamp: '2026-10-02T07:20:04Z',
    },
    {
      stage: 'druggability_assessment',
      agent_name: 'DruggabilityAgent',
      input_summary: 'Assessed tractability buckets across small molecules, antibodies, and PROTAC modalities.',
      output_summary: 'Mapped clinical antibody precedence for TREM2 and small molecule active-site tractability for BACE1.',
      tool_calls: ['opentargets_tractability_query'],
      status: 'success',
      duration_ms: 610.8,
      timestamp: '2026-10-02T07:20:05Z',
    },
    {
      stage: 'compound_screening',
      agent_name: 'CompoundScreeningAgent',
      input_summary: 'Queried ChEMBL bioactivity records and performed in silico binding simulations for top candidates.',
      output_summary: 'Retrieved 5 verified ChEMBL active molecules; predicted binding Kd for 4 synthetic simulation candidates.',
      tool_calls: ['chembl_bioactivity_search', 'run_insilico_screening_simulation'],
      status: 'success',
      duration_ms: 980.6,
      timestamp: '2026-10-02T07:20:06Z',
    },
    {
      stage: 'target_ranking',
      agent_name: 'TargetRankingAgent',
      input_summary: 'Executed 6-factor deterministic target ranking engine with clinical contradiction penalties.',
      output_summary: 'Ranked 5 candidates: TREM2 (#1, 89.4), BACE1 (#2, 82.1), APP (#3, 79.5), APOE (#4, 73.8), PSEN1 (#5, 68.2).',
      tool_calls: ['calculate_deterministic_composite_score'],
      status: 'success',
      duration_ms: 22.0,
      timestamp: '2026-10-02T07:20:07Z',
    },
    {
      stage: 'supervisor_synthesis',
      agent_name: 'SupervisorAgent',
      input_summary: 'Synthesized comprehensive multi-modal dossier and audit trail.',
      output_summary: 'Finalized research report with executive summary and downloadable scientific artifacts.',
      tool_calls: ['generate_research_report'],
      status: 'success',
      duration_ms: 45.3,
      timestamp: '2026-10-02T07:20:07Z',
    },
  ],
};
